# Generated by Django 4.2.7 on 2026-02-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
