# Generated by Django 6.0.2 on 2026-02-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
